name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /root/tgbot
            git pull
            pip3 install -r requirements.txt --break-system-packages -q && systemctl restart tgbot
